USE SuperstoreDB

SELECT COUNT(*) FROM superstore_raw;

SELECT TOP 10 * FROM superstore_raw;

--Creating Customers Table
CREATE TABLE customers
(
    customer_id VARCHAR(50),
    customer_name VARCHAR(100),
    segment VARCHAR(50),
    country VARCHAR(50),
    city VARCHAR(50),
    state VARCHAR(50),
    postal_code INT,
    region VARCHAR(50)
);

--Inserting data
INSERT INTO customers
SELECT DISTINCT
    Customer_ID,
    Customer_Name,
    Segment,
    Country,
    City,
    State,
    Postal_Code,
    Region
FROM superstore_raw;

SELECT COUNT(*) FROM customers;

SELECT * from customers;

--Creating  Product Table
CREATE TABLE products
(
    product_id VARCHAR(50),
    category VARCHAR(50),
    sub_category VARCHAR(50),
    product_name VARCHAR(255)
);

--Inserting data
INSERT INTO products
SELECT DISTINCT
    Product_ID,
    Category,
    Sub_Category,
    Product_Name
FROM superstore_raw;

SELECT COUNT(*) FROM products;

SELECT * FROM products

--Creating Orders Table
CREATE TABLE orders
(
    row_id INT PRIMARY KEY,
    order_id VARCHAR(50),
    order_date DATE,
    ship_date DATE,
    ship_mode VARCHAR(50),
    customer_id VARCHAR(50),
    product_id VARCHAR(50),
    sales DECIMAL(10,2),
    quantity INT,
    discount DECIMAL(5,2),
    profit DECIMAL(10,2)
);

--Inserting data
INSERT INTO orders
SELECT DISTINCT
    Row_ID,
    Order_ID,
    Order_Date,
    Ship_Date,
    Ship_Mode,
    Customer_ID,
    Product_ID,
    Sales,
    Quantity,
    Discount,
    Profit
FROM superstore_raw;

SELECT COUNT(*) FROM orders;

SELECT * FROM orders

-- Verify data inserted into all tables
SELECT TOP 5 * FROM customers;
SELECT TOP 5 * FROM products;
SELECT TOP 5 * FROM orders;


--Section 1: Subquery

--Question 1 .Find orders with sales above average sales
Select 
    order_id,
    customer_id,
    sales
From orders Where sales > (Select AVG(Sales) from orders)
ORDER BY sales DESC

-- Question 2. Find highest sales order for each customer
Select
    order_id,
    customer_id,
    sales
FROM orders o
where sales =
(Select MAX(Sales) from orders where customer_id = o.customer_id)


--Section 2 : CTE

--Question 3. Calculate total revenue generated by each customer

WITH customer_sales AS
(
    SELECT
        customer_id,
        SUM(sales) AS total_sales
    FROM orders
    GROUP BY customer_id
)
SELECT *
FROM customer_sales
ORDER BY total_sales DESC;

--Question 4. Find customers whose total sales are above average (CTE + Subquery)
WITH customer_sales AS
(
    SELECT
        customer_id,
        SUM(sales) AS total_sales
    FROM orders
    GROUP BY customer_id
)

SELECT
    customer_id,
    total_sales,
    (SELECT AVG(total_sales) FROM customer_sales) AS average_sales
FROM customer_sales
WHERE total_sales >
(
    SELECT AVG(total_sales)
    FROM customer_sales
);


--Section 3 : Window Function

--RANK()

-- Question 5. Rank all customers based on total sales

SELECT
customer_id,
SUM(sales) AS total_sales,
RANK() OVER (ORDER BY SUM(sales) DESC) AS customer_rank
FROM orders
GROUP BY customer_id;

--ROW_NUMBER()

--Question 6. Assign row numbers to each order within a customer.
SELECT
    customer_id,
    order_id,
    sales,
    ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY sales DESC) AS row_num
FROM orders;

--Question 7. Display top 3 customers based on total sales.
SELECT *
FROM
(
    SELECT
        customer_id,
        SUM(sales) AS total_sales,
        RANK() OVER(ORDER BY SUM(sales) DESC) AS customer_rank
    FROM orders
    GROUP BY customer_id
) t
WHERE customer_rank <= 3;

--JOIN + CTE + Window Function

--Customer sales summary with ranking

with customer_sales AS
(
    SELECT
        customer_id,
        SUM(sales) AS total_sales
    FROM orders
    GROUP BY customer_id
)
SELECT
    c.customer_name,
    cs.total_sales,
    RANK() OVER(ORDER BY cs.total_sales DESC) AS customer_rank
FROM customer_sales cs
JOIN customers c ON cs.customer_id = c.customer_id;


--BUSINESS Queries (MINI PROJECT)

--Question 1. Who are the top 5 customers?

WITH customer_sales AS
(
    SELECT
        customer_id,
        SUM(sales) AS total_sales
    FROM orders
    GROUP BY customer_id
)
SELECT TOP 5
    customer_id,
    total_sales
FROM customer_sales
ORDER BY total_sales DESC;

--Question 2. Who are the bottom 5 customers?

WITH customer_sales AS
(
    SELECT
        customer_id,
        SUM(sales) AS total_sales
    FROM orders
    GROUP BY customer_id
)
SELECT TOP 5
    customer_id,
    total_sales
FROM customer_sales
ORDER BY total_sales ASC;

--Question 3. Customers who placed only one order

SELECT
    customer_id,
    COUNT(DISTINCT order_id) AS total_orders
FROM orders
GROUP BY customer_id
HAVING COUNT(DISTINCT order_id) = 1;

--Question 4. Customers whose total sales are above average

WITH customer_sales AS
(
    SELECT
        customer_id,
        SUM(sales) AS total_sales
    FROM orders
    GROUP BY customer_id
)

SELECT
    customer_id,
    total_sales,
    (SELECT AVG(total_sales) FROM customer_sales) AS average_sales
FROM customer_sales
WHERE total_sales >
(
    SELECT AVG(total_sales)
    FROM customer_sales
);

--Question 5. What is the highest order value per customer?

SELECT
    order_id,
    customer_id,
    sales AS highest_order_value
FROM orders o
WHERE sales =
(
    SELECT MAX(sales)
    FROM orders
    WHERE customer_id = o.customer_id
);

